### ISSUE TITLE
[TEST] Test MACE - descriptors workflow

### ISSUE THREAD

**Issue by akalikadien** [EPiCs-group/obelix#23]
------------------------------------------------------------------------------------------------------------------------

We need to implement test(s) for the following scenario:

## Description
GIven a ligand/substrate input for MACE. A 3D xyz file needs to be generated with a sensible chemical structure, for which we calculate descriptors.
## Code Reference
[ Permalink to code for which the test is required ]
### Case: 
* Simple square planar structure with just a bidentate ligand and a metal
* Simple square planar structure with a bidentate ligand and two Cl atoms attached to metal

- **Preconditions:** 
* Metal and ligands as input (e.g. SMILES string?)
- **Test Steps:** 
* Run generate_sp function of MACE class
* Use xyz's that are generated as output for this function as input for DescriptorCalculator.generate_morfeus_descriptors function
- **Test Data:** 
* Depends on the type of input for MACE. Currently a string can be given as input, but this string could be read from a file (e.g. in cases of high-throughput usage)
- **Expected Result:** 
* A csv file with a list of descriptors
- **Post-condition:** 
* Check whether csv with descriptors is generated
* Compare csv with a predefined reference

--------------------------------------------------------------------------------------------------------------------------

**Comment by niketagrawal** [comment]
### Bug in MACE
The test fails when run sequentially for two inputs. The final descriptor values produced for the input that is second on the input queue is not consistent with the expected descriptor values for that input, however if the same input is placed first in the queue of the inputs, the descriptor values are consistent.

Upon investigation, it is discovered that the XYZ files generated by MACE for an input are not consistent. If the workflow is run on a list of inputs sequentially, the XYZ files generated for an input differs on the position of the input in the queue.

To reproduce this bug, use the branch reproduce-bug-mace. Run `pytest` from command line. The test passes for the first input in the parametrization list and fails for the second. Switch the order of the input and output to experiment.
