### ISSUE TITLE
[TEST] Test descriptor_calculator for various input types

### ISSUE THREAD

**Issue by akalikadien** [EPiCs-group/obelix#25]
------------------------------------------------------------------------------------------------------------------------

We need to implement test(s) for the following scenario:

## Description
Create csv files with descriptors given a set of xyz files, CREST folders or DFT log files
## Code Reference
- case for xyz files: https://github.com/EPiCs-group/obelix/blob/d95e1ee3d7f345a0490abe7dc8992a7bf3a4854f/obelix/descriptor_calculator.py#L651
- case for CREST folders: https://github.com/EPiCs-group/obelix/blob/d95e1ee3d7f345a0490abe7dc8992a7bf3a4854f/obelix/descriptor_calculator.py#L685
- case for DFT log files: https://github.com/EPiCs-group/obelix/blob/d95e1ee3d7f345a0490abe7dc8992a7bf3a4854f/obelix/descriptor_calculator.py#L778
- examples can be found here: https://github.com/EPiCs-group/obelix/blob/d95e1ee3d7f345a0490abe7dc8992a7bf3a4854f/obelix/descriptor_calculator.py#L864
### Case: 
- Take a set of input files and calculate descriptors
- **Preconditions:** pre-generated xyz files, CREST folders and DFT log files of complexes with a bidentate ligand that needs to be featurized 
- **Test Steps:** 
- Run calculate_morfeus_descriptors on xyz files and CREST folders (separately)
- Run calculate_dft_descriptors_from_log on folder with DFT log files
- **Test Data:** [ if required, data to execute the test cases ]
- **Expected Result:** 
- A csv file with a list of descriptors
- **Post-condition:**
- Check whether csv with descriptors is generated
- Compare csv with a predefined reference
    

--------------------------------------------------------------------------------------------------------------------------

**Comment by akalikadien** [comment]
The examples for testing the descriptors calculator can be found here: [descriptor_calculator_test_examples.zip](https://github.com/user-attachments/files/16028163/descriptor_calculator_test_examples.zip). As discussed, for maximum code coverage we can have 4 test:
* Use an xyz file generated with mace, metal_adduct = pristine
* Use L1_example.xyz, metal_adduct = nbd 
* Use L1_example.log to test the DFT descriptors, metal_adduct = nbd
* Use L40_example/ to test CREST input, metal_adduct = pristine

**Comment by niketagrawal** [comment]
Implementation of this test is being done in the branch [25-test-descriptor-calcultor](https://github.com/EPiCs-group/obelix/tree/25-test-descriptor-calculator)

### Done
- Testcases parametrized for the following metal_adduct and output_type combination: [nbd, xyz files], [pristine, xyz files], [nbd, dft log file]
- testcases: assert descriptor values, index values, filename valus, and element values in the csv file produced

### To do

- [ ] The descriptor values generated by the dft log file (L1_example.log) contains non numeric data. It contains a ‘True’. numpy array comparison fails, so assert descriptor values fails
- [ ] The L40_example/ generates an empty descriptors.csv file. 
-
